spring:
  application:
    name: yan-file
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
server:
  port: 9000
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /




