server:
  port: 8999

spring:
  datasource:
    username: root
    password: 1942951600
    url: jdbc:mysql://localhost:3306/yan?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    #    host: 127.0.0.1
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5
mybatis:
  mapper-locations: classpath*:com/rose/demo/dao/xml/*Dao.xml
  type-aliases-package: com.rose.demo.entity
logging:
  level:
    com.rose.demo.dao: debug

