spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.20:8848
        # \u8BF7\u6C42\u53C2\u6570\u4E2D\u5E26\u4E86 baidu \u5C31\u53BB\u8F6C\u53D1\u5230 http://www.baidu.com
    sentinel:
      transport:
        dashboard: localhost:8333
    gateway:
      routes:
## lb: 所有mall-product的请求都会被截取掉 /api/
#        - id: order_route
#          uri: lb://order
#          predicates:
#            - Host=order.glmall.com
#
#        - id: product_route
#          uri: lb://mall-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: yan_file
          uri: lb://yan-file
          predicates:
            - Path=/api/file/**
          filters:
            - RewritePath=/api/file/(?<segment>.*), /$\{segment}
        - id: yan_database
          uri: lb://yan-database
          predicates:
            - Path=/api/database/**
          filters:
            - RewritePath=/api/database/(?<segment>.*), /$\{segment}
        - id: yan_devops
          uri: lb://yan-devops
          predicates:
            - Path=/api/devops/**
          filters:
            - RewritePath=/api/devops/(?<segment>.*), /$\{segment}
        - id: yan_manage
          uri: lb://yan-manage
          predicates:
            - Path=/api/manage/**
          filters:
            - RewritePath=/api/manage/(?<segment>.*), /$\{segment}
        - id: yan_first
          uri: lb://yan-first
          predicates:
            - Path=/api/first/**
          filters:
            - RewritePath=/api/first/(?<segment>.*), /$\{segment}
        - id: yan_loginUser
          uri: lb://yan-loginUser
          predicates:
            - Path=/api/loginUser/**
          filters:
            - RewritePath=/api/loginUser/(?<segment>.*), /$\{segment}
        # 给netty服务器配送相应的功能
        - id: yan_chatServe
          uri: lb://chatServe
          predicates:
            - Path=/api/chatServe/**
          filters:
            - RewritePath=/api/chatServe/(?<segment>.*), /$\{segment}
#        - id: search_route
#          uri: lb://mall-search
#          predicates:
#            - Host=search.glmall.com
#        - id: auth_route
#          uri: lb://mall-auth-server
#          predicates:
#            - Host=auth.glmall.com
#        - id: seckill_route
#          uri: lb://mall-seckill
#          predicates:
#            - Host=seckill.glmall.com
#        - id: cart_route
#          uri: lb://mall-cart
#          predicates:
#            - Host=cart.glmall.com
#        - id: member_route
#          uri: lb://mall-member
#          predicates:
#            - Host=member.glmall.com

#        # 任何以mall.com结尾的域名转发到mall-product
#        - id: mall_route
#          uri: lb://mall-product
#          predicates:
#            - Host=**.glmall.com,glmall.com,item.glmall.com
server:
  port: 88