spring:
  application:
    name: yan-file
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.20:8848
    sentinel:
      transport:
        dashboard: 192.168.56.20:8333
  redis:
    #    open: false  # 是否开启redis缓存  true开启   false关闭
    host: 192.168.56.20
    port: 6379
server:
  port: 9000
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /



aliyun:
  oss:
    file:
      endpoint: xxxx.aliyuncs.com
      keyid: xxxx
      keysecret: xxxx
      bucketname: xxx
